
const NetworkStatus = {
  STATUS_BAD_GATEWAY: 502,
  STATUS_INTERNAL_SERVER_ERROR: 500,
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_SERVICE_UNAVAILABLE: 503,
  FORBIDDEN:403,
  OK: 200,
}

export default NetworkStatus;