export const Account ={

  TYPE_CUSTOMER : 1,
  TYPE_EMPLOYEE : 2,
  TYPE_VENDOR : 3,

  ACCOUNT_CUSTOMER_TEXT : "Customer",
  ACCOUNT_EMPLOYEE_TEXT : "Employee",
  ACCOUNT_VENDOR_TEXT : "Vendor",


  ACCOUNT_CATEGORY_CUSTOMER: 1,

  ACCOUNT_CATEGORY_EMPLOYEE: 2,

  ACCOUNT_CATEGORY_VENDOR: 3,

  ACCOUNT_CATEGORY_USER: 4,

};