const Feature={
    ENABLE_REPLENISHMENT: "enable_replenishment",
    ENABLE_ORDER: "enable_order",
    ENABLE_TRANSFER: "enable_transfer",
    ENABLE_PRODUCT: "enable_product",
    ENABLE_TICKET: "enable_ticket",
    ENABLE_DELIVERY_ORDER: "enable_delivery_order",
    ENABLE_ACTIVITY: "enable_activity",
    ENABLE_SALE_SETTLEMENT : "enable_sale_settlement",
    ENABLE_PURCHASE: "enable_purchase",
    ENABLE_ATTENDANCE : "enable_attendance",
    ENABLE_STOCK_ENTRY: "enable_stock_entry",
    ENABLE_WISH_LIST: "enable_wish_list",
    ENABLE_FINE: "enable_fine",
    ENABLE_LOCATION: "enable_location",
    ENABLE_CANDIDATE: "enable_candidate",
    ENABLE_VISITOR : "enable_visitor",
    ENABLE_PAYMENT: "enable_payment",
    ENABLE_INSPECTION: "enable_inspection",
    ENABLE_USER: "enable_user",
    ENABLE_BILL: "enable_bill",
    ENABLE_LEAD: "enable_lead",
    ENABLE_ACCOUNT: "enable_account",
    ENABLE_GATE_PASS: "enable_gate_pass",
    ENABLE_CUSTOMER: "enable_customer",
    ENABLE_PURCHASE_ORDER: "enable_purchase_order",
    ENABLE_SALARY: "enable_salary",
    ENABLE_LOCATION_ALLOCATION: "enable_location_allocation",
    ENABLE_REPORT: "enable_report",
    ENABLE_DISTRIBUTION: "enable_distribution",
    ENABLE_SETTING: "enable_setting",
    ENABLE_SYNC: "enable_sync",
    ENABLE_ORDER_PRODUCT: "enable_order_product",
    ENABLE_RECURRING_TASK: "enable_recurring_task",
    ENABLE_BULK_ORDER: "enable_bulk_order",
    ENABLE_CONTACT: "enable_Contact"
}

export default Feature;