const Menu = {
  ACTIVITIES:"ACTIVITIES",
  ORDER: "Order",
  ORDER_PRODUCT: "Order Product",
  PURCHASE: "Purchase",
  REPLENISH: "ProductReplenish",
  STOCK_ENTRY: "StockEntry",
  LOCATION: "Location",
  TRANSFER: "inventoryTransfer",
  PRODUCT: "BrandAndCategoryList",
  WISHLIST: "WishListProducts",
  LAST_SYNC: "Sync",
  SALE_SETTLEMENT: "SalesSettlement",
  ACTIVITY_LIST: "ActivityList",
  ATTENDANCE: "Attendance",
  SETTINGS: "Settings",
  TICKET: "Ticket",
  FINE: "Fine",
  MENU: "Menu",
  DASHBOARD: "Dashboard",
  REPORTS: "Report",
  ORDER_PRODUCT_REPORT: "OrderProductReport",
  ORDER_SUMMARY_REPORT: "OrderSummaryReport",
  ATTENDANCE_REPORT: "AttendanceReport",
  ORDER_REPORT: "Reports",
  ORDER_SALES_SETTLEMENT_REPORT: "OrderSalesSettlementDiscrepancyReport",
  PURCHASE_RECOMMENDATION_REPORT: "PurchaseRecommendationReport",
  TRANSFER_PRODUCT_REPORT_USERWISE : "TransferProductReportUserWise",
  STOCK_ENTRY_REPORT : "StockEntryReport",
  MESSAGES: "Messages",
  DELIVERY: "Delivery",
  DISTRIBUTION : "distributionTransfer"

}
export default Menu
