const tab = {
    ATTACHMENTS: "Attachments",
    CUSTOMER : "Customer",
    GENERAL: "General",
    SUMMARY:"Summary",
    PRODUCTS: "Products",
    TICKET : "Tickets",
    TODAY: "Today",
    ALL: "All",
    LOCATION: 'Location',
    STOCK: "Stock",
    MEDIA : 'Media',
    COMMENT:'Comments',
    ORDERS : 'Orders',
    ORDER_PRODUCTS : 'Order Products',
    PRODUCT : "Product",
    LOCATION : "Location",
    ASSIGNED : "Assigned",
    REPORTED : "Reported",
    ALL : "All",
    HISTORY : "History",
    PURCHASES : "Purchases",
    DELIVERY : "Delivery",
    REPLENISH:"Replenish",
    VIDEO : "Video",
    IMAGES : "Images",
    COMPLETED : "Completed",
    DRAFT : "Draft",
    CANCELLED : "Cancelled",
    PRICE : "Prices",
    MAP : "Map",
    BRAND : "Brands",
    CATEGORY : "Categories",
    REPLENISHED:"Replenished",
    PENDING:"Pending",
    DETAIL:"Detail",
    TYPE:"Type",
    SETTING: "Setting",
    DATE: "Date",
    MONTH: "Month",
    ATTENDANCE: "Attendance",
    FINE: "Fine",
    BONUS: "Bonus",

}

export default tab;